// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPoMMKdgOkA6uusRA8DpB32xfXOlBzXw',
    appId: '1:772738524115:web:b178b1c009b49fb913c526',
    messagingSenderId: '772738524115',
    projectId: 'eyesgo-assignment',
    authDomain: 'eyesgo-assignment.firebaseapp.com',
    storageBucket: 'eyesgo-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsaNzW3VNn0EdDOEwD8tpaRX7LnqR7jJg',
    appId: '1:772738524115:android:04105f0988273c0013c526',
    messagingSenderId: '772738524115',
    projectId: 'eyesgo-assignment',
    storageBucket: 'eyesgo-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBr9gtnQcSGpNaYk50NI_d81jBXXls2Ps',
    appId: '1:772738524115:ios:2cd8fcec1837304913c526',
    messagingSenderId: '772738524115',
    projectId: 'eyesgo-assignment',
    storageBucket: 'eyesgo-assignment.firebasestorage.app',
    iosBundleId: 'com.example.eyegoAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBr9gtnQcSGpNaYk50NI_d81jBXXls2Ps',
    appId: '1:772738524115:ios:2cd8fcec1837304913c526',
    messagingSenderId: '772738524115',
    projectId: 'eyesgo-assignment',
    storageBucket: 'eyesgo-assignment.firebasestorage.app',
    iosBundleId: 'com.example.eyegoAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrPoMMKdgOkA6uusRA8DpB32xfXOlBzXw',
    appId: '1:772738524115:web:b3f9cb3d2d791b1513c526',
    messagingSenderId: '772738524115',
    projectId: 'eyesgo-assignment',
    authDomain: 'eyesgo-assignment.firebaseapp.com',
    storageBucket: 'eyesgo-assignment.firebasestorage.app',
  );
}
