// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cA-MmEiQsvYFnaoYDurFdXiILmYPy7I',
    appId: '1:601856695796:web:4c32af06fcaf37d1e36da1',
    messagingSenderId: '601856695796',
    projectId: 'eyego-assignment',
    authDomain: 'eyego-assignment.firebaseapp.com',
    storageBucket: 'eyego-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQu1isrRLPcTf98xSpqjs81lO_KRaTyf8',
    appId: '1:601856695796:android:52483b19c396cb97e36da1',
    messagingSenderId: '601856695796',
    projectId: 'eyego-assignment',
    storageBucket: 'eyego-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD14v-AEHOMcH5cgcWvr_dTt-IFaGXuec',
    appId: '1:601856695796:ios:6efce70e25f39874e36da1',
    messagingSenderId: '601856695796',
    projectId: 'eyego-assignment',
    storageBucket: 'eyego-assignment.firebasestorage.app',
    iosBundleId: 'com.example.eyegoAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD14v-AEHOMcH5cgcWvr_dTt-IFaGXuec',
    appId: '1:601856695796:ios:6efce70e25f39874e36da1',
    messagingSenderId: '601856695796',
    projectId: 'eyego-assignment',
    storageBucket: 'eyego-assignment.firebasestorage.app',
    iosBundleId: 'com.example.eyegoAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cA-MmEiQsvYFnaoYDurFdXiILmYPy7I',
    appId: '1:601856695796:web:2731ff19d17d5fcce36da1',
    messagingSenderId: '601856695796',
    projectId: 'eyego-assignment',
    authDomain: 'eyego-assignment.firebaseapp.com',
    storageBucket: 'eyego-assignment.firebasestorage.app',
  );
}
